import { RULE_LABELS, type Report, type Severity } from "../types.js";

const ICON: Record<Severity, string> = { error: "🔴", warning: "🟡", info: "🔵" };

/** Render a report as a shareable Markdown document. */
export function toMarkdown(report: Report): string {
  const lines: string[] = [];
  const s = report.summary;
  lines.push("# linklint report", "");
  lines.push(
    `**Overall: ${s.score}/100 (${s.grade})** · ${s.documents} document(s) · ${s.links} link(s) · ` +
      `${s.errors} error(s), ${s.warnings} warning(s), ${s.infos} info`,
    "",
  );
  lines.push(`> Generated by ${report.tool} v${report.version} on ${report.generatedAt}`, "");

  if (s.byRule.length > 0) {
    lines.push("## Issues by rule", "", "| Rule | Count |", "| --- | --- |");
    for (const r of s.byRule) {
      lines.push(`| ${RULE_LABELS[r.rule] ?? r.rule} | ${r.count} |`);
    }
    lines.push("");
  }

  const withIssues = report.documents.filter((d) => d.issues.length > 0);
  if (withIssues.length === 0) {
    lines.push("✅ No broken links or anchors found.", "");
    return lines.join("\n");
  }

  for (const doc of withIssues) {
    lines.push(`## ${doc.path} — ${doc.score}/100 (${doc.grade})`, "");
    for (const i of doc.issues) {
      const loc = i.line ? ` _(line ${i.line})_` : "";
      lines.push(`- ${ICON[i.severity]} ${i.message}${loc}`);
      if (i.detail) lines.push(`  - ${i.detail}`);
      if (i.fix) lines.push(`  - 💡 ${i.fix}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}
